# Change these first
owner: Cloudment # Your GitHub organization or username, where this repository lives
repo: cloudment.github.io # The name of this repository

sites:
  - name: Cloudment Home
    url: https://cloudment.net
  - name: Cloudment Billing
    url: https://my.cloudment.net
  - name: Cloudment Dashboard
    url: https://cmt.gg

status-website:
  cname: status.cloudment.net
  themeUrl: https://status.cloudment.net/main.css
  # baseUrl: /your-repo-name
  logoUrl: https://status.cloudment.net/logo.png
  name: Cloudment
  introTitle: "**Cloudment Status** is the open-source uptime monitor and status page, powered by GitHub Pages."
  introMessage: This is Cloudment's status page which uses **real-time** data from our [GitHub repository](https://github.com/Cloudment/cloudment.github.io).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
