owner: Cloudment

assignees:
  - Zinidia
  - JakesFate

repo: cloudment.github.io

sites:
  - name: Cloudment Home
    url: https://cloudment.net
  - name: Cloudment Billing
    url: https://my.cloudment.net
  - name: Cloudment Dashboard
    url: https://cmt.gg

status-website:
  cname: status.cloudment.net
  links:
    - rel: stylesheet
      href: https://status.cloudment.net/main.css
  logoUrl: https://status.cloudment.net/logo.png
  name: Cloudment
  introTitle: "**Cloudment Status** is the live system status of Cloudment's global edge network."
  introMessage: This is Cloudment's status page which uses **real-time** data from our [GitHub repository](https://github.com/Cloudment/cloudment.github.io).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

i18n:
  footer: Copyright ©2022 All rights reserved [Cloudment](https://cloudment.net)

commitMessages:
  commitAuthorName: "Uptime Bot"

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "* * * * *"